services:
  #mysql service
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - backend

  #php-apache service
  web:
    build: .
    restart: always
    ports:
        - "${APACHE_PORT}:80"
    volumes:
        - ./code:/var/www/html
    environment:
        APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT}
    networks:
        - backend

networks:
  backend:
    driver: bridge